# Generated by Django 3.2.6 on 2021-08-31 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210831_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Comments'},
        ),
    ]
